### ISSUE TITLE
Unrecognized manifest key 'browser_specific_settings'.

### ISSUE THREAD

**Issue by masonc15** [iansinnott/one-dark-tab#1]
Hi,

I've been enjoying this extension but recently started getting this error:
```
Unrecognized manifest key 'browser_specific_settings'.

 "browser_specific_settings": {
    "gecko": {
      "id": "darktab@iansinnott.com"
    }
  },
  ```

Not sure what this means.  Any help would be appreciated.  Thanks!

**Comment by iansinnott** [comment]
Ah yeah, was experimenting with supporting other browsers at one point and this affected chrome compatibility. Please use this branch instead https://github.com/iansinnott/one-dark-tab/tree/chrome-version

**Comment by masonc15** [comment]
Thanks!
